const {
  Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType,
  BorderStyle, ShadingType, LevelFormat, PageBreak
} = require('../.docx-runtime/node_modules/docx');
const fs = require('fs');
const path = require('path');

const C = { red:'8B1A1A', dkRed:'5C0011', blue:'1F3864', gold:'7B5200', grey:'555555', black:'1A1A1A', green:'2E5F2E', purple:'5C2D82', teal:'1A5F5F', warm:'6B3A00' };
const tr=(text,o={})=>new TextRun({text,font:o.font||'Georgia',size:o.size||22,color:o.color||C.black,bold:o.bold,italics:o.italics});
const h1=t=>new Paragraph({heading:HeadingLevel.HEADING_1,children:[tr(t,{font:'Arial',size:38,bold:true,color:C.red})]});
const h2=t=>new Paragraph({heading:HeadingLevel.HEADING_2,children:[tr(t,{font:'Arial',size:28,bold:true,color:C.dkRed})]});
const h3=t=>new Paragraph({heading:HeadingLevel.HEADING_3,children:[tr(t,{font:'Arial',size:24,bold:true,color:C.blue})]});
const body=t=>new Paragraph({spacing:{after:150,line:300},children:[tr(t)]});
const bul=(l,t)=>new Paragraph({numbering:{reference:'bullets',level:0},spacing:{after:90,line:290},children:[tr(l+' — ',{bold:true}),tr(t)]});
const box=(label,t,fill,color)=>new Paragraph({shading:{fill,type:ShadingType.CLEAR},border:{left:{style:BorderStyle.THICK,size:12,color,space:6}},indent:{left:400,right:180},spacing:{before:70,after:160,line:290},children:[tr(label+' — ',{font:'Arial',size:20,bold:true,color}),tr(t,{font:'Arial',size:20,italics:true,color})]});
const reveal=t=>new Paragraph({shading:{fill:'FDF6EE',type:ShadingType.CLEAR},border:{left:{style:BorderStyle.THICK,size:14,color:C.warm,space:8}},indent:{left:500,right:260},spacing:{before:90,after:150,line:320},children:[tr(t,{italics:true,color:'3A2010'})]});
const meta=t=>box('ACCÈS',t,'E8EEF8',C.blue);
const truth=t=>box('VÉRITÉ DU MJ',t,'FFF8E1',C.gold);
const follow=t=>box('RELANCE',t,'E7F1ED',C.teal);
const hand=t=>box('HANDOUT',t,'F3E8FD',C.purple);
const divider=()=>new Paragraph({border:{bottom:{style:BorderStyle.SINGLE,size:6,color:C.red,space:1}},spacing:{before:180,after:180},children:[tr('')]});
const pageBreak=()=>new Paragraph({children:[new PageBreak()]});

const groups = [
  {
    title:'A. RUES, MARCHÉS ET TAVERNE',
    intro:'Rumeurs accessibles aux crieurs, boutiquiers, servantes, clients de tavernes et habitués du Marktplatz. Elles donnent d’abord le pouls de la ville.',
    rumours:[
      {id:'R01',title:'Le pain qui maigrit',where:'Sisters’ Bakery, Old Granary, Marktplatz',sl:'Gossip Accessible (+20), 0 SL ; +2 SL pour le nom du peseur',truth:'DEMI-VRAI. Les boulangers n’affament pas volontairement les pauvres. De faux chitties de l’Old Granary circulent, ce qui pousse plusieurs fournées à être rationnées. Le peseur Kaspar Melle revend de vrais jetons après avoir validé les faux.',text:'« Les miches de la Sisters’ Bakery sont plus légères chaque matin. Ils disent que c’est la farine, mais ma belle-sœur a vu un peseur de l’Old Granary sortir avec les poches pleines de jetons d’argile. Quand le pain rétrécit et que la maison du peseur grandit, il n’y a pas besoin de savoir compter. »',follow:'Observer le kiosque à farine révèle deux séries de chitties presque identiques. Un test d’Trade (Merchant) ou Perception Difficile (−10) distingue les faux.',hand:'H1 — Avis des Maîtres Meuniers sur les chitties contrefaits.'},
      {id:'R02',title:'La treizième heure',where:'Guilde des Horlogers, Magnustor, Old Vixen',sl:'Gossip Intermédiaire (+0), 0 SL',truth:'VRAI, MAIS SANS DANGER. Un apprenti horloger a modifié l’horloge de la guilde pour qu’elle sonne treize coups à minuit et fasse accuser son maître de sénilité. Il cherche maintenant à annuler son propre sabotage.',text:'« L’horloge des Cogsmiths a sonné treize fois la nuit dernière. Trois chiens ont hurlé, une femme a accouché et Herr Wexler a juré avoir vu Morr dans la vitre. Les horlogers disent que ce n’était qu’un ressort. Bien sûr qu’ils disent ça. »',follow:'Un PJ qui vient vérifier surprend l’apprenti avec une échelle, une lime et beaucoup trop d’explications.'},
      {id:'R03',title:'Le duc et le collecteur de crottin',where:'Theatre Variété, Wolf and Hobgoblin, Red Moon',sl:'Gossip Accessible (+20), 0 SL',truth:'VRAI. La nouvelle farce des Mootland Minstrels caricature l’administration d’Altdorf. Elle est financée anonymement par une caisse liée aux Karstadt, mais les acteurs l’ignorent.',text:'« Au Variété, ils jouent une nouvelle pièce où un duc d’Altdorf taxe l’air, la pluie et les crottes de cheval. À la fin, il doit manger ses propres formulaires. On rit tellement qu’un sergent a quitté la salle avant l’entracte. Ils rejouent demain, si la Garde n’égare pas leur licence. »',follow:'À +3 SL, le caissier mentionne qu’un “ami du commerce local” a payé décors et costumes.',hand:'H2 — Programme du Theatre Variété.'},
      {id:'R04',title:'Saint Arnold pleure de la bière',where:'Saint Arnold’s Chapel, Borgun’s Brewery, Dawihafen',sl:'Gossip Accessible (+20), échec ou 0 SL',truth:'FAUX SURNATUREL, VRAI PROBLÈME. Une conduite de la brasserie Borgun fuit dans la maçonnerie de la chapelle. Les “larmes” sont une bière brune très diluée. Le chapelain entretient discrètement le miracle pour financer le toit.',text:'« La statue de saint Arnold pleure brun depuis Festag. Pas du sang : de la bière. Ceux qui ont goûté disent qu’elle guérit les verrues et donne des rêves prophétiques. Le chapelain demande seulement deux sous par gobelet, pour la toiture. »',follow:'Trade (Brewer) ou un simple goût reconnaît une bière Borgun. Le miracle devient une querelle embarrassante entre Dawi et clergé.'},
      {id:'R05',title:'L’expédition des orphelins',where:'Merchant Quarter, Merchants’ Guild school, Bridge House',sl:'Gossip Intermédiaire (+0), +1 SL',truth:'VRAI. Mistress Tüsch veut emmener les enfants observer la flore des Hagercrybs. Le risque de bandits est exagéré, mais les enfants eux-mêmes promettent un désastre comique.',text:'« La maîtresse de l’école des Marchands cherche des bras solides pour conduire vingt-sept orphelins dans les Hagercrybs. Elle promet qu’ils sont polis, disciplinés et qu’un seul d’entre eux mord. La Guilde paie l’escorte ; elle ne rembourse pas les vêtements. »',follow:'C’est une mission secondaire réelle, disponible après la crise ou pour des contacts cherchant un travail honnête.'},
      {id:'R06',title:'L’eau au goût de cuivre',where:'Marktplatz, Town Hall, Temple of Shallya',sl:'Gossip Accessible (+20), 0 SL',truth:'VRAI ET MUNDANE. Une conduite publique a été réparée avec des pièces de cuivre de mauvaise qualité. Aucun poison. Le fournisseur a toutefois facturé du bronze au Conseil.',text:'« La fontaine du Marktplatz donne une eau qui laisse la langue comme une pièce de cuivre. Le Conseil dit que c’est sans danger. Le Conseil boit du vin. Les Shallyans font bouillir leur eau depuis deux jours, alors moi aussi. »',follow:'Une enquête mène à Ubersreik Builders’ Company et à une fraude banale sur les matériaux, sans Chaos ni Skaven.'}
    ]
  },
  {
    title:'B. GUILDES, TRAVAIL ET ARGENT',
    intro:'Rumeurs entendues auprès des artisans, commis, guildes et prêteurs. Elles créent des intérêts qui continuent sans les PJs.',
    rumours:[
      {id:'R07',title:'Des épées qui ne sont pas des épées',where:'Cutlers’ Guild, Metalworkers’ Guild, Artisan’s Repose',sl:'Gossip Intermédiaire (+0), +1 SL',truth:'VRAI. Les couteliers exploitent une faille juridique et vendent des “couteaux” longs de plusieurs pieds. Petronilla Merkle veut découvrir leur secret de fabrication et nuire à la guilde rivale.',text:'« Les Couteliers vendent des lames longues comme mon bras en jurant que ce sont des couteaux. Les Métallurgistes parlent de procès ; les clients parlent surtout du prix. Une lame meilleure pour moins cher, ça finit toujours par quelqu’un qui casse une fenêtre. »',follow:'À +3 SL, le nom de Johann Messing ou de Petronilla Merkle apparaît comme commanditaire potentiel d’espionnage industriel.'},
      {id:'R08',title:'Le charbon vaut de l’argent',where:'Artisans’ Quarter, Fronich Woodcutters, forges',sl:'Gossip Accessible (+20), 0 SL',truth:'VRAI. L’embargo Jungfreud raréfie le charbon. Apprentis et journaliers volent clôtures, caisses et parfois planchers pour nourrir les forges.',text:'« Dans le Quartier des Artisans, on paie maintenant un panier de charbon plus cher qu’un poulet. Les apprentis arrachent les palissades la nuit. Si votre chaise disparaît, ne cherchez pas un voleur : cherchez une forge chaude. »',follow:'Ce bruit peut justifier des prix plus élevés, des coupures d’activité ou une petite émeute devant un dépôt.'},
      {id:'R09',title:'Les caisses sans manifeste',where:'Boatbuilders and Chandlers, Teubrücke, Customs House',sl:'Gossip Difficile (−10), +2 SL',truth:'DEMI-VRAI. Kurt Prochnow fait entrer des livres et rouleaux interdits pour sa bibliothèque du Fractured Eye. Les dockers n’ont vu que des caisses trop légères pour des outils.',text:'« Trois caisses sont entrées chez les constructeurs de barges après minuit, sans marque de douane. Pas assez lourdes pour du métal, trop sèches pour du poisson. Quand le maître Prochnow a vu un docker s’approcher, il a payé une semaine de salaire pour qu’il regarde le fleuve. »',follow:'Suivre les caisses révèle une bibliothèque illégale, pas une cache d’armes. Le contenu peut devenir une aventure future.'},
      {id:'R10',title:'Un shilling pour dénoncer un chirurgien',where:'Physicians’ Guild, Saint Bastian’s Hospital, Shallya',sl:'Gossip Accessible (+20), 0 SL',truth:'VRAI. Doktor Krupp paie pour toute preuve qu’un barber-surgeon effectue des actes réservés. Grat connaît la campagne et la juge mesquine, mais elle ne l’arrête pas.',text:'« La Guilde des Médecins offre un shilling pour le nom d’un barbier qui recoud une plaie à l’intérieur des murs. Apparemment, sauver quelqu’un sans le bon diplôme est plus dangereux que le laisser saigner correctement. »',follow:'Cette rumeur peut atteindre Silas par un patient reconnaissant, un rival ou Grat elle-même.',hand:'H3 — Avis officiel de la Guilde des Médecins.'},
      {id:'R11',title:'Les faux jetons du grenier',where:'Old Granary, Furlisdottir’s Corn Exchange, Marktplatz',sl:'Gossip Difficile (−10), +2 SL',truth:'VRAI. Des chitties contrefaits circulent. Le réseau est petit et purement criminel ; il n’est lié ni à K&H ni au Baron.',text:'« L’Old Granary change ses jetons d’argile chaque matin, mais quelqu’un connaissait le motif avant l’ouverture hier. Les gardes ont cassé les doigts d’un garçon et n’ont trouvé sur lui qu’une miche. Le vrai faussaire portait probablement de meilleurs souliers. »',follow:'Le motif a été copié par un employé du four, qui vend les empreintes à deux sœurs du Fleshmarket.'},
      {id:'R12',title:'Le registre disparu de Stork Loans',where:'Stork Loans, Old Vixen, Magnustor',sl:'Gossip Intermédiaire (+0), +1 SL',truth:'DEMI-VRAI. Un registre de dettes a disparu. Le commis l’a volé pour effacer la dette de son amant, pas pour faire chanter les puissants.',text:'« Chez Stork Loans, un registre entier s’est volatilisé. On dit qu’il contenait les dettes d’un juge, de deux prêtres et d’un homme qui jure être noble quand il a bu. Stork paiera mieux pour le livre que pour le voleur. »',follow:'Le registre véritable ne contient presque que des petits débiteurs. Le retrouver peut gagner beaucoup de gratitude populaire — ou un nouvel ennemi prêteur.'}
    ]
  },
  {
    title:'C. LE TEUFEL, LES DOCKS ET L’OMBRE',
    intro:'Rumeurs de bateliers, contrebandiers, dockers, receleurs et habitants de la Wandiene. Les vérités y sont utiles, mais rarement gratuites.',
    rumours:[
      {id:'R13',title:'Le brandy qui remonte le courant',where:'Boatmen’s Guild, Teubrücke, Customs House',sl:'Gossip Intermédiaire (+0), +1 SL',truth:'VRAI. Une cargaison de brandy bretonnien doit être introduite en fraude. Nixie Dunkelstange cherche des non-membres parce qu’une fuite existe à la Douane.',text:'« Une barge sans lanterne remontera le Teufel cette nuit avec du brandy qui n’existe sur aucun registre. Les bateliers habituels restent à terre : quelqu’un, à la Douane, connaît leurs visages. On cherche des mains nouvelles et des consciences bon marché. »',follow:'Mission secondaire réelle. La cargaison n’a aucun lien avec les Lowhaven ou K&H.'},
      {id:'R14',title:'Little Willi doit beaucoup aux mauvaises personnes',where:'Dockers’ Arms, Unterdaumen Warehouses, Teubrücke',sl:'Gossip Difficile (−10), +2 SL',truth:'VRAI. Little Willi a perdu une cargaison Lowhaven saisie par la Douane. Il cherche à la voler dans un entrepôt pour rembourser sa dette.',text:'« Le fils de Big Willi ne boit plus au Dockers’ Arms. Il reste près de la porte et sursaute quand un Halfling entre. La Douane lui a pris quelque chose qui n’était pas à lui, et les véritables propriétaires n’acceptent pas les excuses en tonneaux vides. »',follow:'À +4 SL, le numéro d’un entrepôt de la Douane peut être obtenu.'},
      {id:'R15',title:'La cloche noyée',where:'Ubersreik Bridge, Rugger’s Boarding House, fishermen',sl:'Gossip Accessible (+20), échec ou 0 SL',truth:'FAUX. Le son vient d’une chaîne de balisage qui frappe une vieille ancre sous le pont lorsque le courant change.',text:'« Une cloche sonne sous le Pont d’Ubersreik à marée basse. Ceux qui l’entendent trois nuits de suite sont retrouvés dans le fleuve, les poches pleines de cailloux. Mon cousin l’a entendue deux fois et il refuse maintenant de dormir. »',follow:'Une inspection règle le mystère. La vieille ancre porte toutefois un blason effacé qui peut nourrir une future histoire.'},
      {id:'R16',title:'Les poissons aux yeux d’argent',where:'Little Teufel, Dawihafen, fish market',sl:'Gossip Intermédiaire (+0), +1 SL',truth:'DEMI-VRAI. Les poissons existent ; des résidus des ateliers de métallurgie se déposent sur leurs yeux. Ils ne sont ni mutants ni prophétiques.',text:'« Les pêcheurs du Petit Teufel remontent des gardons aux yeux d’argent. Les Dawi les refusent, les humains les vendent deux fois plus cher et un apothicaire en a acheté douze. Si vous en mangez un, on dit que vous voyez dans le noir. On ne dit pas combien de temps. »',follow:'Un test de Lore (Science) ou Trade approprié révèle une pollution industrielle. Le responsable paierait pour étouffer l’affaire.'},
      {id:'R17',title:'Felix combat dans un entrepôt sans fenêtres',where:'Tin Spur, Crooked Hammer, Hog Pit vicinity',sl:'Gossip Difficile (−10), +2 SL ; +4 SL pour le Hog Pit',truth:'VRAI. Felix Scite est captif des Lowhaven au Hog Pit. Depuis la mort de Bella, ces combats clandestins sont devenus vitaux pour le clan.',text:'« Felix Scite n’a pas quitté la ville. On l’a vu drogué dans une charrette, puis quelqu’un a entendu sa voix derrière les murs d’un entrepôt sans fenêtres. Les Lowhaven vendent déjà des places pour un combat qu’il n’a pas accepté. »',follow:'À +4 SL ou avec un contact de l’ombre, la description correspond au Hog Pit.',hand:'H4 — Avis de recherche discret pour Felix Scite.'},
      {id:'R18',title:'Mercy achète un nom',where:'Dunkelfeucht, Teubrücke, Gilded Cage survivors',sl:'Gossip Difficile (−10), +2 SL',truth:'VRAI. Mercy Lowhaven paie d’abord pour identifier le meurtrier de Bella. Elle n’a pas encore confirmé Kaspar au début du 13.',text:'« Mercy Lowhaven ne paie pas encore pour une tête. Elle paie pour un nom : celui qui a tranché la gorge de Bella à la Cage. Une couronne pour un témoin, cinq pour une certitude. Après les funérailles, le tarif changera de sens. »',follow:'Un témoignage crédible suffit à activer la prime sur Kaspar le lendemain.'},
      {id:'R19',title:'Une taupe sous le Baron',where:'Gilded Cage, Baron’s territory, Kat House',sl:'Gossip Difficile (−10), +3 SL',truth:'VRAI. Rolf Vane renseignait les Lowhaven. Les rumeurs ne donnent pas encore son nom, mais sa conduite pendant l’assaut attire l’attention.',text:'« Otto n’avait pas prévenu tous ses propres hommes avant la Cage. Il y a une taupe chez le Baron, quelqu’un qui a su trop tard que les Lowhaven avaient été avertis. Les paris ne portent pas sur son nom, mais sur le nombre de jours avant qu’on retrouve ses dents. »',follow:'À +4 SL, un témoin se souvient d’un homme du Baron cherchant Bella plutôt que le coffre.'},
      {id:'R20',title:'Werner achète les rives',where:'Boatmen’s Guild, warehouses, black market',sl:'Gossip Difficile (−10), +2 SL',truth:'VRAI. Werner consolide les quais et les barques pendant que la ville regarde Otto. Certains achats servent indirectement la chaîne de ravitaillement de K&H, mais presque personne ne le sait.',text:'« Werner l’Anguille achète des barques trouées, des hangars vides et des dettes de bateliers. Il ne marchande même pas. Otto a gagné une salle pleine de tables cassées ; Werner, lui, achète le fleuve morceau par morceau. »',follow:'Suivre les achats peut mener à des passeurs, à Günther ou à une fausse piste de contrebande avant d’atteindre le ravitaillement de K&H.'}
    ]
  },
  {
    title:'D. TEMPLES, MORTS ET MAUVAIS PRÉSAGES',
    intro:'Rumeurs recueillies auprès des fidèles, fossoyeurs, pénitents, guérisseurs et superstitieux. Les sources parlent avec conviction, pas nécessairement avec vérité.',
    rumours:[
      {id:'R21',title:'Le Sorcier Gris a tué Jannik',where:'High Temple of Sigmar, Pious Cup, Wizards’ Way',sl:'Gossip Accessible (+20), 0 SL',truth:'FAUX. Hannah Baumann a tiré sur Jannik à bout portant pendant leur fuite. Ricker exploite le silence d’Engel pour construire un récit utile.',text:'« Jannik a été retrouvé à quelques pas de la tour d’Engel. Qui d’autre pouvait le tuer sans être vu ? Les prêtres ne l’accusent pas encore, mais ils demandent pourquoi un homme courageux meurt et qu’un sorcier refuse même d’ouvrir sa porte. »',follow:'À +3 SL, un témoin se souvient d’avoir entendu un coup de feu ordinaire, pas un phénomène magique.'},
      {id:'R22',title:'Le champion sans reflet',where:'Chapel of Ulric, Tin Spur, bathhouses',sl:'Gossip Difficile (−10), +2 SL',truth:'DEMI-VRAI. Gestaltenstark est bien un Child of Ulric, mais l’absence de reflet est une superstition. Il évite les miroirs parce qu’il déteste voir les signes de ses transformations.',text:'« Une servante du Tin Spur jure que Gestaltenstark n’apparaît pas dans les miroirs. Il les couvre avant ses combats et paie en argent neuf. Le Denvater Kretschmer a demandé qu’on cesse d’en parler, ce qui est exactement ce qu’un homme dit quand il veut qu’on cesse d’en parler. »',follow:'Le miroir ne prouve rien. Les horaires du champion, ses absences et son médaillon sont de meilleures pistes.'},
      {id:'R23',title:'Les alliances prédites aux Sept Voiles',where:'Morgenseite, Seven Veils, salons',sl:'Gossip Intermédiaire (+0), +1 SL',truth:'DEMI-VRAI ET DANGEREUX. Friedrich von Happe gagne l’influence de familles riches par des consultations astrologiques. Plusieurs clients lui remettent des bijoux “pour purifier leur destinée”.',text:'« Aux Sept Voiles, Friedrich peut dire qui vous épouserez en lisant la buée d’un miroir. Trois fiancées de la Morgenseite lui ont déjà confié leurs alliances avant la cérémonie. Il promet de les rendre quand les étoiles seront favorables. Les étoiles semblent avoir des goûts coûteux. »',follow:'À +3 SL, le père de Johanna est cité comme client fréquent. Cette piste mène à l’Order of the Unblinking Eye.'},
      {id:'R24',title:'Les bandages de Shallya disparaissent',where:'Temple of Shallya, Saint Bastian’s, Fleshmarket',sl:'Gossip Intermédiaire (+0), +1 SL',truth:'VRAI, MAIS MUNDANE. Un aide-soignant vole des rouleaux propres pour les revendre aux combattants clandestins du Hog Pit. Il ignore que Felix y est détenu.',text:'« Le Temple de Shallya manque de bandages alors que ses réserves étaient pleines avant Magnustag. Les prêtresses accusent les blessés d’en prendre trop. Les blessés accusent les rats. Moi, j’accuserais celui qui vend des rouleaux propres au Fleshmarket après la tombée du jour. »',follow:'Suivre le revendeur donne une autre voie vers le Hog Pit sans impliquer directement les Lowhaven.'},
      {id:'R25',title:'La tombe que Morr refuse',where:'Morr’s Field, Gravediggers, northern road',sl:'Gossip Accessible (+20), échec ou 0 SL',truth:'FAUX SURNATUREL. Les fossoyeurs refusent une inhumation parce que la famille n’a pas payé les frais et que le cercueil est trop large pour la parcelle achetée.',text:'« À Morr’s Field, une tombe se remplit de terre toute seule chaque fois qu’on la creuse. Le mort était collecteur d’impôts, alors même le sol n’en veut pas. Les fossoyeurs demandent trois couronnes pour essayer ailleurs. »',follow:'Une négociation ou quelques bras règlent le problème. Le défunt possédait toutefois un carnet de taxes que plusieurs voisins aimeraient brûler.'},
      {id:'R26',title:'Les nouveaux pénitents de la Pious Cup',where:'Pious Cup, North Temple, nearby alleys',sl:'Gossip Difficile (−10), +2 SL',truth:'VRAI. Hannah, Ricker, Ursula et Ingrid utilisent la Pious Cup pour se cacher, recruter et légitimer leur récit. Ils se dispersent dès que des étrangers posent trop de questions.',text:'« La Pious Cup sert le thé à des gens qui ne touchent pas leur tasse. Une jeune femme armée reste toujours près de la porte, et les vieilles dames l’appellent “sœur” même si personne ne connaît son nom. Ils prient pour Jannik, mais ils ferment les volets quand on demande qui l’a vu mourir. »',follow:'À +4 SL, la description de la jeune femme correspond à Ingrid.'}
    ]
  },
  {
    title:'E. SALONS, ALTDORF ET POUVOIR CIVIQUE',
    intro:'Rumeurs des commis, domestiques, marchands aisés et clubs patriotiques. Elles montrent la bataille pour définir qui a le droit de gouverner Ubersreik.',
    rumours:[
      {id:'R27',title:'Le pain Karstadt',where:'Merchant Quarter, Karstadt Estate, temples',sl:'Gossip Accessible (+20), 0 SL',truth:'VRAI ET CALCULÉ. Les Karstadt financent du pain, du charbon et de petites avances après Magnustag. L’aide est réelle ; chaque reçu, file d’attente et témoin construit l’image d’une famille capable de gouverner.',text:'« Les Karstadt paient deux mille miches et du charbon pour les familles touchées par Magnustag. Pas de sermon, pas d’uniforme d’Altdorf : on donne son nom, on reçoit un jeton et on repart avec de quoi manger. Les gens se souviennent de qui ouvre un grenier quand le Conseil écrit encore le formulaire. »',follow:'À +3 SL, Josef Specht est identifié comme l’organisateur. Les listes de bénéficiaires constituent aussi un précieux réseau politique.',hand:'H5 — Jeton de secours Karstadt.'},
      {id:'R28',title:'Une visite après minuit',where:'Town Hall, Karstadt Estate, Old Vixen',sl:'Gossip Difficile (−10), +2 SL',truth:'DEMI-VRAI. Josef Specht a rencontré un secrétaire de Maler tard le soir. Hellin Karstadt n’était pas présente. Le but était d’offrir une ligne de crédit au Conseil contre une influence future.',text:'« Une voiture Karstadt a attendu derrière l’Hôtel de Ville après minuit, rideaux fermés. Au matin, le secrétaire de Maler portait un manteau neuf et le Conseil parlait soudain d’un fonds de reconstruction. Personne n’achète le pouvoir ; on lui offre simplement un siège confortable. »',follow:'Un commis peut confirmer Specht, mais pas Hellin. La contrepartie n’existe encore que sous forme de promesse.'},
      {id:'R29',title:'Les lettres de von Dabernick',where:'Magnustor, coaching inns, Patriot’s Club',sl:'Gossip Intermédiaire (+0), +1 SL',truth:'VRAI. Von Dabernick écrit à Altdorf après Magnustag pour décrire une ville ingouvernable et demander davantage d’autorité ou de troupes.',text:'« Von Dabernick envoie des lettres à Altdorf plus vite que les cochers ne changent de chevaux. Il appelle la Cage, les pamphlets et les gobelins des preuves qu’Ubersreik ne peut se gouverner seule. Les Karstadt appellent cela une candidature très longue au poste de geôlier. »',follow:'Intercepter une lettre confirmerait son ton, mais créerait un risque sérieux avec l’administration impériale.'},
      {id:'R30',title:'Le capitaine et les oiseaux chanteurs',where:'Morgenseite gardens, Emperor’s Rest, servants',sl:'Gossip Intermédiaire (+0), 0 SL',truth:'VRAI ET INUTILE. Un officier d’Altdorf capture des oiseaux rares pour les offrir à sa fiancée. Il n’est ni espion ni cultiste, seulement riche et détestable.',text:'« Un capitaine d’Altdorf paie des gamins pour voler les oiseaux des jardins de la Morgenseite. Il en veut un bleu avant Sigmartag et promet une couronne. Lady Kisaiya menace de faire fouetter le prochain enfant trouvé dans ses roses. »',follow:'Petite histoire autonome : protection des enfants, vol mondain ou occasion de ridiculiser un officier.'},
      {id:'R31',title:'Les serviteurs du Palais Bruner',where:'Bruner Palace, salons, servants’ entrances',sl:'Gossip Difficile (−10), +2 SL',truth:'DEMI-VRAI. Trois serviteurs sont bien partis ; les raisons sont dettes, grossesse et mauvais traitements ordinaires. Heinrich multiplie les dons religieux par anxiété familiale, pas pour un crime précis.',text:'« Trois serviteurs Bruner ont quitté le palais en une semaine. Heinrich donne de l’or à chaque temple comme s’il voulait acheter le pardon en gros. Les domestiques ne s’accordent pas sur ce qu’ils ont vu, seulement sur le fait qu’ils ne veulent plus dormir sous ce toit. »',follow:'Une enquête produit plusieurs secrets humiliants, mais aucun grand complot. Excellent red herring pour des joueurs méfiants.'},
      {id:'R32',title:'La femme en noir de la Diète',where:'Patriot’s Club, coaching houses, pamphleteers',sl:'Gossip Difficile (−10), +3 SL',truth:'FAUX. Cette histoire vient d’un pamphlet d’Ottokar fondé sur deux témoignages incompatibles. Elle persiste parce qu’elle donne un visage simple à l’annexion.',text:'« La veille du vote contre les Jungfreud, une femme vêtue de noir est entrée à la Diète avec une lettre scellée. Grande, accent du Middenland, gants rouges. Les troupes d’Altdorf attendaient déjà à la frontière. Ottokar connaît le sceau sur la lettre, mais refuse encore de l’imprimer. »',follow:'Chaque témoin décrit une taille, un accent et une couleur de gants différents. Aucune femme unique ne correspond.'},
      {id:'R33',title:'Deux tarifs à la Douane',where:'Customs House, Teubrücke, Merchant Quarter',sl:'Gossip Intermédiaire (+0), +1 SL',truth:'DEMI-VRAI. Certains officiers impériaux font passer les réquisitions militaires sans inspection, tandis que les marchands locaux subissent des délais et frais ordinaires. Ce n’est pas un tarif écrit, mais l’effet est réel.',text:'« À la Douane, une caisse d’Altdorf passe avec un salut ; une caisse d’Ubersreik attend avec un formulaire. Ils jurent que le tarif est le même. Bien sûr : le tarif du papier est le même, c’est seulement nous qui devons le remplir. »',follow:'Plusieurs marchands sont prêts à témoigner dans le Herald. Aucun ne veut signer seul.',hand:'H6 — Relevé comparatif anonyme des délais de douane.'},
      {id:'R34',title:'Les tunnels sous la Morgenseite',where:'Dawi taverns, Morgenseite cellars, builders',sl:'Gossip Accessible (+20), échec ou 0 SL',truth:'FAUX, FONDÉ SUR UNE VÉRITÉ. Les Dawi possèdent bien un réseau de tunnels séparé, mais il ne débouche pas sous les chambres des nobles comme le prétend la rumeur.',text:'« Les Dawi peuvent entrer dans toutes les caves de la Morgenseite sans ouvrir une porte. Ils ont des tunnels sous chaque maison noble et comptent les bouteilles de vin pour savoir qui prépare une guerre. Un maçon a trouvé une rune derrière le garde-manger des Araworn. »',follow:'Les Dawi éjectent poliment mais fermement les intrus. La rune du garde-manger n’est qu’une marque de tailleur de pierre.'},
      {id:'R35',title:'Rudi paie une dette invisible',where:'Crooked Hammer, Watchstation, docks',sl:'Gossip Difficile (−10), +3 SL',truth:'DEMI-VRAI. Rudi est bien sous pression, mais pas à cause du jeu : K&H le font chanter. Ses paiements et rencontres ressemblent à une dette pour qui ne connaît pas le contexte.',text:'« Le sergent Rudi ne joue plus, ne boit plus et compte chaque porte quand il entre dans une salle. Quelqu’un lui prend de l’argent ou lui tient la gorge. Il a rencontré un homme des rats près des quais, mais il avait l’air plus effrayé de son ami que de la Garde. »',follow:'À +4 SL, le contact peut être décrit assez précisément pour reconnaître Günther.'},
      {id:'R36',title:'Les feux verts de Magnustag',where:'Morgenseite roofs, Watch Barracks vicinity, firework sellers',sl:'Gossip Intermédiaire (+0), +1 SL',truth:'DEMI-VRAI. Quelques témoins ont aperçu une lueur verdâtre, mais la majeure partie du récit est contamination de mémoire et superstition. Le warpstone existe dans le dispositif skaven, pas dans tous les feux tirés ce soir-là.',text:'« Les dernières fusées de Magnustag ont brûlé vert au-dessus du Magnustor. Pas vert comme du cuivre : vert comme des yeux dans une cave. Le Guet a ramassé les débris avant l’aube. Une femme affirme que les rats de son grenier se sont mis à marcher en cercle. »',follow:'Les débris publics sont ordinaires. Un fragment provenant réellement du dispositif ou de l’atelier réagit autrement sous examen d’Engel.'}
    ]
  }
];

const children=[];
children.push(new Paragraph({alignment:AlignmentType.CENTER,spacing:{before:500,after:70},children:[tr('SEMAINE 2',{font:'Arial',size:54,bold:true,color:C.red})]}));
children.push(new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:90},children:[tr('RUMEURS D’UBERSREIK',{font:'Arial',size:44,bold:true,color:C.dkRed})]}));
children.push(new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:70},children:[tr('36 notes révélables pour Gossip Tests et scènes de ville',{font:'Arial',size:25,italics:true,color:C.grey})]}));
children.push(divider());
children.push(h1('MODE D’EMPLOI'));
children.push(body('Chaque entrée contient un texte joueur prêt à copier dans une note VTT, puis des informations réservées au MJ. Ne révélez jamais la ligne “Vérité du MJ”. Choisissez d’abord un lieu, une profession ou un contact pertinent : un test de Gossip ne doit pas produire la même conversation au Temple de Shallya et au Dockers’ Arms.'));
children.push(bul('0–1 SL','Révélez une rumeur commune du quartier. La source n’offre aucun détail supplémentaire.'));
children.push(bul('2–3 SL','Révélez une rumeur locale ou professionnelle et sa première piste concrète.'));
children.push(bul('4+ SL','Révélez une rumeur d’initié, un nom précis ou le handout associé.'));
children.push(bul('Échec simple','Vous pouvez révéler une rumeur colorée marquée FAUX, sans prétendre que le test a établi sa véracité.'));
children.push(bul('Échec de −2 SL ou pire','Le PJ attire l’attention, froisse le milieu ou devient lui-même le sujet d’une rumeur.'));
children.push(box('PRINCIPE','Une rumeur n’est pas une réponse d’oracle. Elle rapporte ce qu’une personne croit, répète ou veut faire croire. Même une rumeur vraie peut attribuer la mauvaise cause.','FDE8E8',C.red));
children.push(h2('Distribution conseillée'));
children.push(bul('Une demi-journée de recherche','Une note sur réussite ; une seconde à +3 SL ou davantage.'));
children.push(bul('Un contact établi','Abaissez la difficulté d’un cran dans son milieu, mais donnez-lui un prix social : boisson, faveur, secret ou promesse.'));
children.push(bul('Rumeurs centrales','R17–R21 et R35–R36 font avancer les intrigues des PJs. N’en donnez pas plus de deux lors d’une même collecte.'));
children.push(bul('Vie de la cité','R01–R16 et R22–R34 empêchent Ubersreik de devenir un simple tableau de quêtes. Laissez certaines ne mener nulle part de dangereux.'));

for(const group of groups){
  children.push(pageBreak());
  children.push(h1(group.title));
  children.push(body(group.intro));
  for(const r of group.rumours){
    children.push(h2(`${r.id} — ${r.title}`));
    children.push(meta(`${r.where}. ${r.sl}.`));
    children.push(reveal(r.text));
    children.push(truth(r.truth));
    children.push(follow(r.follow));
    if(r.hand) children.push(hand(r.hand));
  }
}

children.push(pageBreak());
children.push(h1('INDEX RAPIDE PAR LIEU'));
children.push(body('Choisissez une ligne lorsque les joueurs annoncent simplement un quartier ou une taverne sans préciser davantage leur méthode.'));
children.push(bul('Marktplatz / Merchant Quarter','R01, R05, R06, R11, R27, R28, R33.'));
children.push(bul('Artisans / Magnustor','R02, R07, R08, R10, R12, R36.'));
children.push(bul('Teubrücke / Wandiene','R03, R13–R20, R24.'));
children.push(bul('Morgenseite / salons','R23, R28–R34.'));
children.push(bul('Temples','R04, R10, R21–R26, R31.'));
children.push(bul('Guet / Crooked Hammer','R18–R21, R26, R29, R35–R36.'));

const styles={default:{document:{run:{font:'Georgia',size:22}}},paragraphStyles:[
  {id:'Normal',name:'Normal',run:{font:'Georgia',size:22,color:C.black},paragraph:{spacing:{after:120,line:300}}},
  {id:'Heading1',name:'Heading 1',basedOn:'Normal',next:'Normal',quickFormat:true,run:{size:38,bold:true,font:'Arial',color:C.red},paragraph:{spacing:{before:480,after:200},outlineLevel:0}},
  {id:'Heading2',name:'Heading 2',basedOn:'Normal',next:'Normal',quickFormat:true,run:{size:28,bold:true,font:'Arial',color:C.dkRed},paragraph:{spacing:{before:360,after:140},outlineLevel:1}},
  {id:'Heading3',name:'Heading 3',basedOn:'Normal',next:'Normal',quickFormat:true,run:{size:24,bold:true,font:'Arial',color:C.blue},paragraph:{spacing:{before:240,after:100},outlineLevel:2}}
]};
const numbering={config:[{reference:'bullets',levels:[{level:0,format:LevelFormat.BULLET,text:'•',alignment:AlignmentType.LEFT,style:{paragraph:{indent:{left:720,hanging:360},spacing:{after:80,line:290}},run:{font:'Georgia',size:22}}}]}]};
const doc=new Document({numbering,styles,sections:[{properties:{page:{size:{width:11906,height:16838},margin:{top:1000,right:1000,bottom:1000,left:1000}}},children}]});

const out=path.resolve(__dirname,'..','output');
const handouts=path.resolve(__dirname,'..','player_handouts');
fs.mkdirSync(out,{recursive:true});
fs.mkdirSync(handouts,{recursive:true});

const playerMd=[];
playerMd.push('# Rumeurs d’Ubersreik — notes VTT révélables','', '> Copier uniquement le corps de la note choisie. Les codes servent au renvoi dans le dossier du MJ.','');
for(const group of groups){
  playerMd.push(`## ${group.title.replace(/^[A-E]\. /,'')}`,'');
  for(const r of group.rumours){
    playerMd.push(`### ${r.id} — ${r.title}`,'',r.text,'');
  }
}

Promise.all([
  Packer.toBuffer(doc).then(b=>fs.writeFileSync(path.join(out,'week2_rumour_dossier.docx'),b)),
  fs.promises.writeFile(path.join(handouts,'week2_rumour_notes_player.md'),playerMd.join('\n'),'utf8')
]).then(()=>console.log(`Generated rumour dossier (${groups.reduce((n,g)=>n+g.rumours.length,0)} notes) and player-note source.`));
